---
- name: 'DNF : Add repos'
  become: True
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl | default(omit) }}"
    metalink: "{{ item.metalink | default(omit) }}"
    gpgkey: "{{ item.gpgkey }}"
    gpgcheck: "{{ item.gpgcheck }}"
  loop: "{{ pkgs_dnf_repos }}"
  loop_control:
    label: "{{ item.name }}"
  tags: ['dnf']

- name: 'DNF : Install base packages'
  become: True
  dnf:
    name: "{{ pkgs_dnf_base }}"
    disable_gpg_check: True
  tags: ['dnf']

- name: 'DNF : Install packages'
  become: True
  dnf:
    name: "{{ pkgs_dnf_packages }}"
  tags: ['dnf']
